### ISSUE TITLE
Seeking clarification about implementation of "SemVer templates"

### ISSUE THREAD

**Issue by joewiz** [expath/expath-pkg-java#11]
In reviewing https://github.com/eXist-db/public-repo/issues/72, I began trying to understand how eXist itself (rather than public-repo) implements the EXPath Package spec's semver pattern. I realized that before we considered any requests for eXist's public-repo app, we had to understand how eXist interprets the spec. Once we understand eXist's behavior, then we'll be on much firmer ground with making any necessary adjustments to public-repo. Since eXist's logic for package and processor dependencies seems to be housed here in `expath-pkg-java` and not in `org.exist.repo`, I thought I'd best ask here. My questions here are:

- Does `expath-pkg-java` implement "SemVer templates" as defined in the EXPath Package spec? 
- What exactly is the logic `expath-pkg-java` applies when assessing semver-min and semver-max values that are expressed as "SemVer templates"?
- Does the `expath-pkg-java` diverge from this aspect of the spec?

The relevant section of the spec is [5.1 Package Dependency](http://expath.org/spec/pkg#pkgdep):

> The [`semver`, `semver-min`, and `semver-max`] attributes use [SemVer](http://semver.org/) to define the set of acceptable versions for the secondary package. We use only the syntax of SemVer, and define in addition the format of **a SemVer template** as being either a SemVer version number or a subpart of it (i.e. only the major version, or the major and the minor versions, or the major, the minor and the patch version). For instance 1.9 is a valid SemVer template (because it does not have any patch number), while 1.9.0 and 1.9.23 are actual version numbers compatible with this template.
> 
> If the `semver` attribute is used, the secondary package version must be compatible with this template. If `semver-min` is used, the secondary package version must be either compatible with that SemVer template, or greater than it. If `semver-max` is used, the secondary package version must be either compatible with that SemVer template, or lower than it. For instance, with `semver-min="2.3"` and `semver-max="3"`, any version of the secondary package which is equal or above 2.3.0 and strictly below 4.0.0 is valid (that is, 2.3.0, 3.0.0, 3.99.87, etc.)

As I read this example, the spec is saying in order for a "secondary package" to conform to the dependency expression `semver-min="2.3" semver-max="3"`, its version must be:

> `2.3.0` <= VERSION < `4.0.0`

In other words, the spec is telling us to interpret `semver-min="2.3"` as follows: 

1. Apply a kind of semver-aware `floor()` to the bottom of the range 2.3.0-2.4.0 implied by `2.3`
2. Coerce this floor into a proper semver, `2.3.0`
3. Use an *inclusive comparison* to enforce semver-min: `2.3.0` <= VERSION.

And we should interpret `semver-max="3"` as:

1. Apply a semver-aware `ceiling()` to the top of the range 3.0.0-4.0.0 implied by `3`.
2. Coerce this ceiling into a proper semver, `4.0.0`
3. Use an *exclusive comparison* to enforce semver-max: VERSION < `4.0.0`.

I'm curious whether @duncdrum's change in https://github.com/expath/expath-pkg-java/commit/55f42cb2b7cefe9cbd19f6969c5c0a7e74c2801f does really conform to the spec? 

The imported `org.expath.pkg.repo.deps` defines the `matchesMin` method as `>=` and the `matchesMax` as `<=`. So wasn't the original code correct in adding the condition `!matches`—so that the handling of the semver-max is effectively `<`, as the spec requires? In other words, doesn't @duncdrum's commit cause the behavior to be `<=` on the right-hand-side, or the following?

> `2.3.0` <= VERSION <= `4.0.0`

I'd appreciate anyone's help in understanding whether the behavior of `expath-pkg-java` conforms to the spec with regard to package and processor dependency or if there are any divergences? Once I understand this, I'll be better able to assess eXist's public-repo app and implement any necessary changes.

**Comment by joewiz** [comment]
@duncdrum Forgive me, I think your code was correct because it is comparing proper semvers, not semver templates. 

It seems that I should have been looking at https://github.com/expath/expath-pkg-java/blob/master/pkg-java/src/main/java/org/expath/pkg/repo/deps/Semver.java#L123-L167 for the code that handles "SemVer templates" - but please correct me if I'm wrong. 

If that is the right place, then the presence of the `>= 0` in `matchesMax` makes me wonder if this comparison is *exclusive* as the spec states? 

And is this code used in both package and processor dependency resolution? Are "SemVer templates" supported in both package and processor dependency resolution?

**Comment by joewiz** [comment]
Conclusion from today's eXist Community Call is:

1. Does expath-pkg-java implement "SemVer templates" as defined in the EXPath Package spec?

> Yes.

2. What exactly is the logic expath-pkg-java applies when assessing semver-min and semver-max values that are expressed as "SemVer templates"?

> As described above.

3. Does the expath-pkg-java diverge from this aspect of the spec?

> All tests (including those @adamretter just added locally - could you please commit these, Adam?) show it's in line with the spec, though we are not sure about how `-SNAPSHOT` is interpreted, i.e., since `5.0.0-SNAPSHOT` is less than `5.0.0` in SemVer 2.0, would a `semver-min="5"` template match `5.0.0-SNAPSHOT`, or would `semver-max="6"` match `6.0.0-SNAPSHOT`?

**Comment by adamretter** [comment]
@joewiz Sure... I did commit and push the tests during the call also ;-) See - https://github.com/expath/expath-pkg-java/commit/cc87293c2b185ad12f9d37ca969219953062511a

**Comment by joewiz** [comment]
@adamretter Super! Thanks!
